
[general]

	[general.general]
		timestamps_format = 0
		streamer_mode = false
		modcore_warning = false
		essential_gui_scale = 0
		gui_scale = true
		network_messages = true
		prompt_when_visiting_trusted_hosts = false

	[general.online_status]
		show_essential_indicator_on_tab = true
		show_essential_indicator_on_nametags = true

	[general.experience]
		alternate_character_customizer = false
		essential_full = true
		enable_essential = true
		show_menus = true

	[general.friends]
		invite_friends = true

[hidden]

	[hidden.hidden]
		wardrobesortoption = 0
		screenshotbrowseritemsperrow = 3
		spspinnedgamerules = ""

[privacy]

	[privacy.general]
		display_current_server = true
		friend_privacy_settings = 0

[notifications]

	[notifications.general]
		disable_all_notifications = false
		host_world_ip_warning = true
		screeenshot_toast_duration = 1
		update_notifications = false
		message_sound = true
		online_friend_alert = true
		message_notifications = true
		group_message_notifications = true

[quality_of_life]

	[quality_of_life.general]
		auto_refresh_session = true

	[quality_of_life.fullscreen]
		windowed_fullscreen = true

	[quality_of_life.discord_integration]
		discord_rich_presence = false
		show_username_and_avatar = false
		set_activity_status_on_discord = false
		allow_ask_to_join = false
		show_current_server = false

	[quality_of_life.zoom]
		smooth_zoom_animation = false
		toggle_to_zoom = false
		smooth_camera_when_zoomed = true

	[quality_of_life.screenshots]
		vanilla_screenshot_message = false
		essential_screenshots = true
		screenshot_sounds = true

[cosmetics]

	[cosmetics.general]
		cosmetic_armor_handling = 0
		hide_cosmetics_on_server_skins = false
		disable_cosmetics = false
		hide_cosmetics_on_server_skin_override = false
		disable_cosmetics_in_inventory = false
		show_my_armor = 0
		"show_other_players'_armor" = 0

